### ISSUE TITLE
Überlieferung: preview

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#10]
Please remove the preview completely to minimize the maintenance effort.

For example, the preview does not work correctly in Firefox and Chrome.

-> Please remove preview for the three chapters Visualisierung der Urkundenproduktion, Kopien und Dorsualnotizen, Häufigkeit und Vorkommen von Dorsualnotizschichten, and Visualisierung der Dorsualschichten

**Comment by HelenaSabel** [comment]
@jsvt-AG: It’s not an issue at all to take out the `<iframe>` element that does this, but it’s working properly in both Firefox and Chrome, so I am wondering why it fails for you (and if maybe it’s the same issue that is causing problems for you in the visualization of the documents)

**Comment by HelenaSabel** [comment]
@jsvt-AG Done!
