### ISSUE TITLE
Shortened Link

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#11]
After feedback from our communications manager:
Could you exchange the link pointing to the Staatsarchv-Page (in the footer and introductory page):

www.ag.ch/staatsarchiv instead of https://www.ag.ch/de/verwaltung/bks/kultur/kulturpflege/bibliothek-archiv/staatsarchiv

In the footer:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/766a33ce-b386-4b70-a3d4-4376c4ee3ee2)

Einleitung:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/af46b41c-8178-46fd-a3ab-e9ceb3e0026c)

**Comment by HelenaSabel** [comment]
@jsvt-AG  Done!
