### ISSUE TITLE
Einleitung: Links in content

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#13]
Adjustment of display when clicking on individual chapters in the table of contents: Chrome, Edge, and Safari
Mozilla seems ok

Chrome/Edge: For _Die Geschichte Königsfeldens; Transkriptions- und Datierungsrichtlinien, Datendownload; Abkürzungen und Symbole; Bibliografie; Berichterstattung_ I have noticed that it does not jump to the correct place in the text. Chapter title should be clearly visible.

Safari: All chapters

See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/3cf3da17-417b-414d-b180-c195ee6a7943)

**Comment by HelenaSabel** [comment]
@jsvt-AG ready for testing

**Comment by jsvt-AG** [comment]
Note for myself:
For Firefox: ok

For Edge/Chrome still : Transkriptions- und Datierungsrichtlinien, Datendownload; Abkürzungen und Symbole; Bibliografie; Berichterstattung; Mitarbeitende und Finanzierung; Vorgeschlagene Zitierweise

e.g.
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/094aedf4-15e3-499e-a635-9a6f55509669)

Testing for Safari is open

**Comment by HelenaSabel** [comment]
@jsvt-AG Improved the location of the anchors and at least in my version of Chrome it looks ok  (it’s likely that for Vorgeschlagene Zitierweise was already working considering that it’s at the bottom of the page)

**Comment by jsvt-AG** [comment]
Great!
Note for myself: Testing in Safari is still open

**Comment by HelenaSabel** [comment]
@jsvt-AG I cannot test Safari and if I separate the anchors more, then it would start to not match with the other browsers...

**Comment by jsvt-AG** [comment]
alright, so let's just leave it this way. no worries
