### ISSUE TITLE
Einleitung: Removal of links

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#14]
Thanks to Andreas' feedback, we should remove the links to SSRQ. Please remove the links in the following places.

- Die digitale Edition 
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/580a31dd-b8d7-45bf-b74d-cb50e1b36e3a)

- Transkriptions- und Datierungsrichtlinien, Datendownload
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/2122fd62-0123-4f8d-bdb8-9d1d68002098)

**Comment by HelenaSabel** [comment]
@jsvt-AG: does the link Datierungsrichtlinien in the footer remains?

**Comment by jsvt-AG** [comment]
@HelenaSabel 
Link for Datierungsrichtlinien: https://web.archive.org/web/20240119174026/https://www.ssrq-sds-fds.ch/wiki/Datierungsrichtlinien

**Comment by jsvt-AG** [comment]
Great!
Only thing is, footer changes on document-page (e.g. https://koenigsfelden.sources-online.org/data/docs/U-17_0001.xml)

See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/9b2c325b-3d8f-4305-804c-d4ce4e3565f5)

**Comment by HelenaSabel** [comment]
@jsvt-AG I copied the HTML from the old app in which there were plenty of elements to facilitate a multi-lingual website (which were unnecessary in this case). The “translation file” was not uploaded properly in the document page, and that explains why you saw different contents. I cleaned up the HTML and it works as it should.

**Comment by jsvt-AG** [comment]
Perfect, thank you for the update!

@HelenaSabel 
But now the old link (https://www.ssrq-sds-fds.ch/wiki/Datierungsrichtlinien) for Datierungsrichtlinien is displayed again, sorry :)

**Comment by HelenaSabel** [comment]
Apologies... I forgot to update my local copy when I first changed the link, hence the problem of coming back to a previous version...

**Comment by jsvt-AG** [comment]
Perfect! Thanks for the update!
