### ISSUE TITLE
Register: Date information on detail page

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#15]
Date on detail page is incorrect in this case: https://koenigsfelden.sources-online.org/detail.html?ref=per029001
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/b21f1a68-9628-4033-9b89-18415437fee9)

The complete period (here: 14th century) should actually be specified. Could you please check how the dates on the detail pages are created if entire periods are actually given? And correct this if necessary.

**Comment by HelenaSabel** [comment]
@jsvt-AG:
What would be the preferred format:  `14. Jh.`  or `1.1.1301-30.12.1400`?

If you select the first one, to be consistent, should we change dates like `10.3.1429` to `10. März 1429`?

**Comment by jsvt-AG** [comment]
@HelenaSabel 

I would prefer the indication "14. Jh.".
Thank you for the question about consistency, you are absolutely right. It would then be preferable to use 10. März 1429, but I'm a little worried that this could lead to a very wide column. That's why I would stick to the inconsistency, if that is not a mediavistic no-go.

**Comment by HelenaSabel** [comment]
@jsvt-AG Let me show some screenshots with the formatted date, so you can see how it would look like.

Place register:

![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/7a36fde1-fce2-4a08-bc6c-e8b3901ba3c9)


Person register:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/13bf2a2b-8fec-4c33-907a-95ed11d15f34)

I personally think it looks ok like that, but, if it doesn’t convince you, for ranges we can display text lile  `14. Jh.` or `Anfang 16. Jh.` and for exact dates the date with the format `D.M.Y`.

**Comment by jsvt-AG** [comment]
Great!
