### ISSUE TITLE
Überlieferung: Links in content

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#16]
Adjustment of display when clicking on individual chapters in the table of contents: Chrome and Edge
Mozilla seems ok, Safari is still open

For _Visualisierung der Urkundenproduktion, Kopien und Dorsualnotizen; Archivordnung von 1570 in Bern_ I have noticed that it does not jump to the correct place in the text. Chapter title should be clearly visible.

See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/7f9a7333-0fa1-46a8-87f0-df06b2da0b4b)

**Comment by HelenaSabel** [comment]
Done!

**Comment by jsvt-AG** [comment]
comment for myself:
for edge/chrome still open: Häufigkeit und Vorkommen von Dorsualnotizschichten; Visualisierung der Dorsualschichten; Archivordnungen; Archivordnung von 1570 in Bern

e.g.
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/528ec9a2-24f6-4732-8a1b-71ff0dee03b4)

Firefox: all good

Testing open for safari

**Comment by jsvt-AG** [comment]
great!
note for myself: testing open for safari
