### ISSUE TITLE
Dokumente: View Digitalisat

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#28]
For all tested Browsers: View Digitalisat does not open, when on third position (or other than second position)

See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/1c7ff5f6-61a3-4b73-ae1c-a844bdd25553)

-> if it would take too long to fix: A restriction as in view position 1 is also perfectly fine. Meaning: On position 2 the view Digitalisat would always be per default. The option to open the view Digitalisat would not show on any other position.
See Position 1:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/c3958dcb-69af-445f-8ec2-7f584aa262d6)

**Comment by HelenaSabel** [comment]
@jsvt-AG Due to lack of time, I implemented the workaround you suggest (facsimile only available in second panel), which I know it’s not a very satisfactory solution, but it was the best I could do with the time left....

**Comment by jsvt-AG** [comment]
@HelenaSabel looks great.

Only thing is: once the facsimile is closed it can't be reopened (only if the page is reloaded).

See: 
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/e3483570-c646-4722-982d-6055ae098893)

**Comment by HelenaSabel** [comment]
@jsvt-AG: That was intentionally. The issue is that the viewer only works properly when it’s loaded with the initial window load, and it only works in that panel. You can change the views of the panel, but then if you close it an open a new panel it wouldn’t work (and you would need to reload the page anyway).

**Comment by jsvt-AG** [comment]
Alright, thank you very much for the explanation. Thus we can close the ticket as the app works as intended.
