### ISSUE TITLE
Start: Searchbox

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#3]
Would it be possible to update the text displayed in the Searchbox
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/53061003-68a3-43cc-9cde-f7a7459c4961)

-> Geben Sie die Nummer eines Dokuments (inkl. vorgestellten Nullen!) ein und drücken Sie den Knopf, um unmittelbar das entsprechende Dokument zu öffnen. 
z. B. 0727/01

**Comment by HelenaSabel** [comment]
@jsvt-AG done and deployed!

**Comment by jsvt-AG** [comment]
Perfect! Thank you very much!

**Comment by jsvt-AG** [comment]
Just a small thing that came up while showing the website to our archivists:

- Could you delete the "!" ?
- And could you correct the justification (break between text and searchbox) as following:
- 
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/db1dfad2-e685-4472-b489-60baa3647f41)

at the moment it looks like this (with wide spaces)
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/0eed9e0b-c6b6-4fe4-a411-6c429dfd03c1)

**Comment by HelenaSabel** [comment]
@jsvt-AG I deleted the !, but I don’t see the issue with the text alignment:


![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/9287a237-3b1c-4e6b-b448-2f1edf91cc27)

**Comment by jsvt-AG** [comment]
Thank you very much! 

For us it looks in all browsers like this:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/6c809717-ddf4-4979-8695-b4de33d53696)

Idea from Stefan: Could a linebreak after "[...] öffnen." resolve it?

**Comment by HelenaSabel** [comment]
@jsvt-AG Can you check again after cleaning the browser cache? I cannot understand why you see it like that. Even if I change the width of the window, the text remains perfectly aligned (both in Firefox and Chrome)

**Comment by jsvt-AG** [comment]
Hi @HelenaSabel 
I deleted all the data, but it unfortunately still looks the same:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/0b3a4512-d91f-44d4-9587-13517034cc9d)
At some point, when I make the window smaller, it looks fine. But if the window is opened full page it looks like the screenshot above.

Mh, left-alignment would mean a different design-decision.

What do you think: Could it be an option to have the entire block at the end of the page, if the justified option can't be fixed? 
It already is this way, when making the window very small.
See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/9098ee14-3ac3-4947-be1f-197a5758e395)

**Comment by jsvt-AG** [comment]
Unfortunately the wide spaces are still displayed. So probably left alignment is the best solution (something for the next iteration).

**Comment by HelenaSabel** [comment]
@jsvt-AG: have you checked after cleaning-up the browser cache? (in case you are seeing the previous CSS?) 

With my changes from yesterday, automatic hyphenation should happen instead of wide white spaces.

**Comment by jsvt-AG** [comment]
Now it looks perfectly fine! Thank you so much!
