### ISSUE TITLE
Header: "Start"

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#30]
Dear Helena, according to our communication's manager the home page should be clearly indicated in the header, so she recommends that we include the text "Start" between the logo and "Einleitung"; clicking on it would also take a user to the home page.
Could you insert "Start"? 

See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/4deeaad1-3739-4e06-af2f-e1ea5df19a25)

**Comment by HelenaSabel** [comment]
Done!

**Comment by jsvt-AG** [comment]
comment for myself:
- edge, firefox, chrome: wonderful
- open: safari

**Comment by jsvt-AG** [comment]
perfect in safari as well!
