### ISSUE TITLE
Einleitung: textual adaption

### ISSUE THREAD

**Issue by StAAG-dLZA** [Staatsarchiv-Aargau/koenigsfelden-app#31]
Dear Helena

Could you please update this part:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/160004835/e82127ff-0dd0-4595-b6af-f06a03b9c92d)

as follows:
Einen experimentellen und visuellen Zugriff erhalten Sie über den Reiter "Überlieferung". Sie finden auf dieser Seite Links auf externe Seiten, die von Peter Dängeli (Data Science Lab und Digital Humanities), Vlad Atanasiu (Digital Humanities) und Tobias Hodel (Digital Humanities) der Universität Bern gepflegt werden.

(sorry I didn't mention that earlier)

**Comment by jsvt-AG** [comment]
perfect, thank you!
