### ISSUE TITLE
NEW: Dokumente/Einleitung: "Diplomatische Fassung"

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#39]
Feedback from Tobias: Could you change "Textnahe Fassung" to "Diplomatische Fassung"?

As well as this sentence (Einleitung):

Dazu muss auf der Dokumentenseite die View "textnahe Fassung" gewählt werden.

to

-> Dazu muss auf der Dokumentenseite die View "diplomatische Fassung" gewählt werden.

**Comment by jsvt-AG** [comment]
perfect! Thank you very much!

**Comment by jsvt-AG** [comment]
>As well as this sentence (Einleitung):
>
>Dazu muss auf der Dokumentenseite die View "textnahe Fassung" gewählt werden.
>
>to
>
> Dazu muss auf der Dokumentenseite die View "diplomatische Fassung" gewählt werden.

See: 
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/a1385149-3ab4-4f40-b84c-c9beb96e3b1c)

@HelenaSabel Could this be updated as well?

**Comment by HelenaSabel** [comment]
@jsvt-AG: Maybe you need to refresh the page? I see the corrected version (or am I missing something)
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/aa2d930d-2a3a-44a6-b849-f2f1b368dcc2)

**Comment by jsvt-AG** [comment]
@HelenaSabel 
you are absolutely right! Sorry for that!
