### ISSUE TITLE
Einleitung: Headers

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#4]
Please insert titel at corresponding text block
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/ca2d957d-aa44-48c4-92b6-b9eca1699689)

**Comment by HelenaSabel** [comment]
@jsvt-AG done!

**Comment by jsvt-AG** [comment]
Great, thank you very much!
