### ISSUE TITLE
Dokumente: "Anfrage an den Server schlug fehl"

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#5]
There still seem to be difficulties in opening individual documents (Samples so far)). 

For Edge: 
U-17_0973:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/3a055f09-003d-4bfb-b7e0-31df22c6717b)

For Firefox, Chrome:
For example: U-17_0727/01; U-17_0727/02, AA_0428_0002, U-17_0003, AA_0428_0005a
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/8642b1f3-675e-42d5-a0ef-331dede7a119)

For Safari: Testing is open

In our last meeting, we discussed whether there was a systematic way to test this behavior. Is there one? And could you check this? Otherwise we will try to check every entry manually

**Comment by HelenaSabel** [comment]
@jsvt-AG 

- In Firefox and Chrome, I have no issues at all opening: 
   -  https://koenigsfelden.sources-online.org/data/docs/U-17_0973.xml
   - https://koenigsfelden.sources-online.org/data/docs/U-17_0727_01.xml
   - https://koenigsfelden.sources-online.org/data/docs/U-17_0727_01.xml
   - https://koenigsfelden.sources-online.org/data/docs/U-17_0003.xml
   - https://koenigsfelden.sources-online.org/data/docs/AA_0428_0005a.xml

- From where did you access the files you mention? Was it after performing a query? If so, could you reproduce the error again and give me more details?

- My colleague @iwonagg is preparing the automatic test which tries out all the links from [the results page](https://koenigsfelden.sources-online.org/index.html) and check that they are opened without errors. Maybe she can let us know here when her test will be ready.

**Comment by jsvt-AG** [comment]
Sorry, I saw that too late as it was a very irregular pattern. It's once again down to the proxy settings in our canton. I'll take care of the unlocking.

Thank's for the automatic test!
