### ISSUE TITLE
Register - Familien/Organisationen: sorting

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#9]
If all persons are displayed, something does not seem to be working correctly with the sorting.

Edge, Firefox, Chrome, Safari
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/79fc5ee1-29ba-4b7d-ad43-46cc66624610)

**Comment by HelenaSabel** [comment]
@jsvt-AG corrected!
